### ISSUE TITLE
Build process

### ISSUE THREAD

**Issue by florianorpeliere** [florianorpeliere/KFE#1]
Requirement in the gulpfile.

* [x] the generated app must be in a dist/ folder
* [x] compile JSX
* [x] generate package.json of the electron app from src/package.json.tpl with infos from the package.json of the project
* [x] livereload electron

**Comment by ThomasCrvsr** [comment]
Requirement in the gulpfile.js :
* the generated app must be in a dist/ folder
* transpile ES6 code into ES5 code with Babel
* generate package.json of the electron app from src/package.json.tpl with infos from the package.json of the project

**Comment by florianorpeliere** [comment]
Check `generate app` and `generate package.json`. Commit 7c25ffde03742524c3bd814083855771ab412400
