### ISSUE TITLE
Example course package

### ISSUE THREAD

**Issue by ThomasCrevoisier** [florianorpeliere/KFE#7]
Make a package for a course as an example. This will be used as a basis to work on.

**Comment by ThomasCrvsr** [comment]
Maybe add a JSON overview of every steps ? What do you think @florianorpeliere ?

**Comment by florianorpeliere** [comment]
```javascript
//formation.json 

{
   title: '',
   description: '',
   authors: '',
   dependencies: [
   
   ],
   exercices: [
      {
         title: '',
         description: '',
         specFile: 'name.spec.js',
         contract: ['testObjectAssign'],
         initialCodeFile: 'name.init.js' 
      }
   ]
}
```

**Comment by ThomasCrvsr** [comment]
If we keep this kind of details about exercises, we will have redundancies because we already have, for each exercise, a `description.json` file. What should we put for each exercise in `formation.json` ? Maybe just a title and the path to the exercise folder ?
